
-- 문제 1 --
SELECT DEPARTMENT_NAME 학과명 , CATEGORY 계열
FROM TB_DEPARTMENT;

-- 문제 2 --
SELECT CAPACITY "학과별 정원", DEPARTMENT_NAME || "의 정원은" || CAPACITY || "명 입니다."
FROM TB_DEPARTMENT;

-- 문제 3 --
SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE DEPARTMENT_NO = 001
AND ABSENCE_YN = 'Y'
AND SUBSTR(STUDENT_SSN, 8, 1) = 2;

-- 문제 4 --
SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE STUDENT_NO IN ('A513079', 'A513090', 'A513091', 'A513110', 'A513119');

-- 문제 5 --
SELECT DEPARTMENT_NAME, CATEGORY
FROM TB_DEPARTMENT
WHERE CAPACITY BETWEEN 20 AND 30 ;

-- 문제 6 --
SELECT PROFESSOR_NAME
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO IS NULL;

-- 문제 7 --
SELECT DEPARTMENT_NO
FROM TB_STUDENT
WHERE DEPARTMENT_NO IS NULL;

-- 문제 8 --
SELECT CLASS_NO
FROM TB_CLASS
WHERE PREATTENDING_CLASS_NO IS NOT NULL;

-- 문제 9 --
SELECT DISTINCT CATEGORY
FROM TB_DEPARTMENT;

-- 문제 10 --
SELECT STUDENT_NO, STUDENT_NAME, STUDENT_SSN
FROM TB_STUDENT
WHERE ABSENCE_YN = 'N'
AND STUDENT_NO LIKE 'A21%'
AND STUDENT_ADDRESS LIKE '전주%';

------------------------------------------------------

------------------ 함수 ------------------

-- 문제 1
SELECT STUDENT_NO 학번, STUDENT_NAME 이름, TO_CHAR(ENTRANCE_DATE, 'YYYY/MM/DD') 입학년도
FROM TB_STUDENT
WHERE DEPARTMENT_NO = 002
ORDER BY 입학년도;

-- 문제 2
SELECT PROFESSOR_NAME , PROFESSOR_SSN 
FROM TB_PROFESSOR
WHERE PROFESSOR_NAME NOT LIKE '___';

-- 문제 3
SELECT PROFESSOR_NAME 교수이름, ABS(SUBSTR(PROFESSOR_SSN, 1, 2) + 1900 - 2023) 나이
FROM TB_PROFESSOR
WHERE SUBSTR(PROFESSOR_SSN, 8, 1) = '1' 
ORDER BY 나이;

-- 문제 4
SELECT SUBSTR(PROFESSOR_NAME, 2, 2) 이름
FROM TB_PROFESSOR
WHERE PROFESSOR_NAME LIKE '___';

-- 문제 5 ***
SELECT STUDENT_NO , STUDENT_NAME 
FROM TB_STUDENT
WHERE ABS(TO_DATE(SUBSTR(STUDENT_SSN, 1, 2)) - ENTRANCE_DATE) = '19';

-- 문제 6
SELECT TO_DATE('2020-12-25', 'DAY')
FROM DUAL;







































